# Generated by Django 5.2 on 2025-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='employees',
            field=models.ManyToManyField(related_name='appointments', to='api.employee'),
        ),
    ]
