# Generated by Django 5.2 on 2025-06-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appointment_employee_appointment_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='employees',
            new_name='attendees',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'position': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='api.employee'),
        ),
    ]
